### ISSUE TITLE
Is the Runge-Kutta integrator in the OptimTraj multiple shooting method vectorized for greater speed and efficiency?

### ISSUE THREAD

**Issue by stumarcus576** [MatthewPeterKelly/OptimTraj#17]
Is the Runge-Kutta integrator in the OptimTraj multiple shooting method vectorized for greater speed and efficiency?

**Comment by MatthewPeterKelly** [comment]
The Runge-Kutta method is vectorized as much as is possible. This makes it a bit harder to read, but provides a significant speed improvement. That being said, RungeKutta can be much slower than the other methods because the sequence of sub-step evaluations in RungeKutta cannot be vectorized, since each sub-step depends on the previous sub-step.
